# Generated by Django 4.2.2 on 2023-09-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PandaStatus',
            fields=[
                ('panda_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.IntegerField()),
                ('experience_points', models.IntegerField()),
                ('eaten_bomboo_count', models.IntegerField()),
                ('owned_normal_bomboo_count', models.IntegerField()),
                ('owned_premium_bomboo_count', models.IntegerField()),
            ],
        ),
    ]
