# Generated by Django 4.2.2 on 2023-09-06 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('expiration_date', models.DateField()),
                ('storage_status', models.CharField(max_length=100)),
                ('last_update_datetime', models.DateTimeField(auto_now=True)),
                ('regisration_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
